import React, { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { Menu, X } from "lucide-react";
import { useNavigate } from "react-router-dom";

// Sidebar data
const categories = [
  {
    id: "packages-deals",
    name: "Packages Deals (4)",
    sub: [
      { id: "classic-skin", name: "Classic Skin Package (6)" },
      { id: "prime-skin", name: "Prime Skin Package (7)" },
      { id: "wax", name: "Wax Package (5)" },
      { id: "hair", name: "Hair Package (3)" },
    ],
  },
  {
    id: "facial",
    name: "Facial (3)",
    sub: [
      { id: "all-type", name: "All Type Skin Facial (14)" },
      { id: "dry-skin", name: "Dry Skin Facial (2)" },
      { id: "oily-skin", name: "Oily Skin Facial (2)" },
      { id: "anti-aging", name: "Luxury Facial (4)" },
    ],
  },
  {
    id: "nail-art",
    name: "Nail Art (1)",
    sub: [{ id: "nail-art", name: "Nail Art (10)" }],
  },
  {
    id: "clean-up",
    name: "Clean Up (1)",
    sub: [{ id: "clean-up", name: "Clean Up (4)" }],
  },
  {
    id: "make-up",
    name: "Make Up (6)",
    sub: [
      {
        id: "party-make-up",
        name: "Party Makeup (3)",
      },
      { id: "engagement-make-up", name: "engagement Makeup (3)" },
      { id: "bridal-make-up", name: "Bridal Makeup (3)" },
      { id: "group-deals", name: "Group Deals (2)" },
      { id: "hair-styling", name: "Hair Styling (5)" },
      { id: "saree-draping", name: "Saree Draping (1)" },
    ],
  },
  {
    id: "bleach",
    name: "Bleach (1)",
    sub: [{ id: "bleach", name: "Bleach (11)" }],
  },
  {
    id: "de-tan",
    name: "De-Tan (1)",
    sub: [{ id: "de-tan", name: "De-Tan (9)" }],
  },
  {
    id: "waxing",
    name: "Waxing (4)",
    sub: [
      { id: "honey-waxing", name: "Honey Waxing (15)" },
      { id: "rica-waxing", name: "Rica Waxing (16)" },
      { id: "rica-brazilian", name: "Rica Brazilian Waxing (8)" },
      { id: "rica-roll-on", name: "Rica Roll-On Waxing (10)" },
    ],
  },
  {
    id: "medi-pedi",
    name: "Medi & Pedi (3)",
    sub: [
      { id: "medi-pedi", name: "Medi Pedi Combo (4)" },
      { id: "medicure", name: "Medicure (5)" },
      { id: "pedicure", name: "Pedicure (4)" },
    ],
  },
  {
    id: "hair-care",
    name: "Hair Care (5)",
    sub: [
      { id: "hair-cut", name: "Hair Cut (10)" },
      { id: "hair-spa", name: "Hair Spa (5)" },
      { id: "hair-color", name: "Hair Colourimg (9)" },
      { id: "hair-highlights", name: "Hair Highlights (1)" },
      { id: "hair-treatments", name: "Hair Treatments (6)" },
    ],
  },
  {
    id: "pre-bridal",
    name: "Pre-Bridal (1)",
    sub: [{ id: "pre-bridal", name: "Pre Bridal (3)" }],
  },
  {
    id: "threading",
    name: "Threading (1)",
    sub: [{ id: "threading", name: "Threading (6)" }],
  },
];

// Service packages data
const services = {
  "classic-skin": [
    {
      id: 1,
      title: "VLCC Facial Package",
      price: 899,
      oldPrice: 1590,
      discount: "43% Off",
      duration: "75 MINS",
      img: "/vlcc.jpg",
    },
    {
      id: 2,
      title: "VLCC Skin Package",
      price: 1299,
      oldPrice: 1999,
      discount: "35% Off",
      duration: "120 MINS",
      img: "/skin.jpg",
    },
    {
      id: 3,
      title: "Homely Groom Package",
      price: 1699,
      oldPrice: 2700,
      discount: "37% Off",
      duration: "130 MINS",
      img: "/groom.jpg",
    },
    {
      id: 4,
      title: "Blogger Beauty Package",
      price: 1899,
      oldPrice: 2800,
      discount: "32% Off",
      duration: "120 MINS",
      img: "/blog.jpg",
    },
    {
      id: 5,
      title: "Glam Up",
      price: 2149,
      oldPrice: 3856,
      discount: "44% Off",
      duration: "175 MINS",
      img: "/glam.jpg",
    },
    {
      id: 6,
      title: "Home Salon Gift",
      price: 1899,
      oldPrice: 3490,
      discount: "46% Off",
      duration: "120 MINS",
      img: "/salon.jpg",
    },
  ],
  "prime-skin": [
    {
      id: 1,
      title: "O3+ Whitening Package",
      price: 2489,
      oldPrice: 3899,
      discount: "36% Off",
      duration: "120 MINS",
      img: "/o3.jpg",
    },
    {
      id: 2,
      title: "Essentials Package",
      price: 2799,
      oldPrice: 4899,
      discount: "43% Off",
      duration: "180 MINS",
      img: "/essen.jpg",
    },
    {
      id: 3,
      title: "Makeover Package",
      price: 2749,
      oldPrice: 4850,
      discount: "43% Off",
      duration: "240 MINS",
      img: "/makeo.jpg",
    },
    {
      id: 4,
      title: "Just Chill",
      price: 2299,
      oldPrice: 3899,
      discount: "41% Off",
      duration: "150 MINS",
      img: "/chill.jpg",
    },
    {
      id: 5,
      title: "Corporate Girl",
      price: 2799,
      oldPrice: 5255,
      discount: "47% Off",
      duration: "180 MINS",
      img: "/corp.jpg",
    },
    {
      id: 6,
      title: "Tip To Toe",
      price: 2799,
      oldPrice: 5158,
      discount: "46% Off",
      duration: "200 MINS",
      img: "/tip.jpg",
    },
    {
      id: 7,
      title: "Charming Beauty",
      price: 3299,
      oldPrice: 6500,
      discount: "49% Off",
      duration: "290 MINS",
      img: "/charm.jpg",
    },
  ],
  "wax": [
    {
      id: 1,
      title: "Honey Wax Package",
      price: 529,
      oldPrice: 999,
      discount: "47% Off",
      duration: "60 MINS",
      img: "/honey.jpg",
    },
    {
      id: 2,
      title: "Honey Bikini Wax Package",
      price: 1119,
      oldPrice: 2550,
      discount: "50% Off",
      duration: "70 MINS",
      img: "/bikibi.jpg",
    },
    {
      id: 3,
      title: "RICA Wax Package",
      price: 849,
      oldPrice: 1650,
      discount: "49% Off",
      duration: "45 MINS",
      img: "/rica.jpg",
    },
    {
      id: 4,
      title: "RICA Bikini Wax Package",
      price: 1799,
      oldPrice: 3229,
      discount: "44% Off",
      duration: "120 MINS",
      img: "/rbikini.png",
    },
    {
      id: 5,
      title: "Honey Wax With Meni-Pedi Package",
      price: 2120,
      oldPrice: 3589,
      discount: "41% Off",
      duration: "120 MINS",
      img: "/hw.jpg",
    },
  ],
  "hair": [
    {
      id: 1,
      title: "Root Touchup & Wax",
      price: 1499,
      oldPrice: 2015,
      discount: "26% Off",
      duration: "75 MINS",
      img: "/root.jpg",
    },
    {
      id: 2,
      title: "Keratin Hair SPA Package",
      price: 1349,
      oldPrice: 2200,
      discount: "39% Off",
      duration: "120 MINS",
      img: "/keratin.jpg",
    },
    {
      id: 3,
      title: "Global Package",
      price: 3149,
      oldPrice: 5800,
      discount: "46% Off",
      duration: "180 MINS",
      img: "/global.jpg",
    },
  ],
  "all-type": [
    {
      id: 1,
      title: "VLCC Facial Package",
      price: 999,
      oldPrice: 1590,
      discount: "37% Off",
      duration: "75 MINS",
      img: "/vlcc.jpg",
    },
    {
      id: 2,
      title: "VLCC Skin Package",
      price: 1399,
      oldPrice: 2150,
      discount: "35% Off",
      duration: "90 MINS",
      img: "/skin.jpg",
    },
    {
      id: 3,
      title: "VLCC Insta Glow Package",
      price: 799,
      oldPrice: 999,
      discount: "20% Off",
      duration: "45 MINS",
      img: "/insta.jpg",
    },
    {
      id: 4,
      title: "VLCC Fruit Facial",
      price: 599,
      oldPrice: 999,
      discount: "40% Off",
      duration: "45 MINS",
      img: "/frut.jpg",
    },
    {
      id: 5,
      title: "Aroma Magic Bridal Glow Facial",
      price: 1199,
      oldPrice: 1500,
      discount: "20% Off",
      duration: "45 MINS",
      img: "/facial1.avif",
    },
    {
      id: 6,
      title: "Lotus Herbals - Whitening & Glow Facial",
      price: 949,
      oldPrice: 1450,
      discount: "35% Off",
      duration: "45 MINS",
      img: "/lotus.jpg",
    },
    {
      id: 7,
      title: "Lotus Herbals- Diamond Facial",
      price: 949,
      oldPrice: 1500,
      discount: "37% Off",
      duration: "45 MINS",
      img: "/dia.jpg",
    },
    {
      id: 8,
      title: "O3+ Whitening Facial - For All Type Skin",
      price: 1599,
      oldPrice: 2500,
      discount: "36% Off",
      duration: "45 MINS",
      img: "/o3w.jpg",
    },
    {
      id: 9,
      title: "O3+ Power Brightening Facial",
      price: 1600,
      oldPrice: 2600,
      discount: "25% Off",
      duration: "45 MINS",
      img: "/o3b.jpg",
    },
    {
      id: 10,
      title: "O3+ Shine 7 Glow Facial",
      price: 1800,
      oldPrice: 2922,
      discount: "40% Off",
      duration: "45 MINS",
      img: "/o3.jpg",
    },
    {
      id: 11,
      title: "O3+ Bridal Facial - For Radiant & Glowing Skin",
      price: 2399,
      oldPrice: 4999,
      discount: "52% Off",
      duration: "60 MINS",
      img: "/lotushd.jpg",
    },
  ],
  "dry-skin": [
    {
      id: 1,
      title: "Blossom Kochhar Diamond Facial",
      price: 1098,
      oldPrice: 1599,
      discount: "31% Off",
      duration: "45 MINS",
      img: "/blo.jpg",
    },
    {
      id: 2,
      title: "SARA Green Apple Facial By O3+",
      price: 1099,
      oldPrice: 1599,
      discount: "31% Off",
      duration: "45 MINS",
      img: "/sara.jpg",
    },
  ],
  "oily-skin": [
    {
      id: 1,
      title: "Lotus WhiteGlow",
      price: 949,
      oldPrice: 1499,
      discount: "37% Off",
      duration: "45 MINS",
      img: "/ol.jpg",
    },
    {
      id: 2,
      title: "O3+ Sea White Facial",
      price: 1599,
      oldPrice: 2598,
      discount: "38% Off",
      duration: "45 MINS",
      img: "/ol1.jpg",
    },
  ],
  "anti-aging": [
    {
      id: 1,
      title: "VLCC Skin Tightening",
      price: 749,
      oldPrice: 999,
      discount: "25% Off",
      duration: "45 MINS",
      img: "/aa.jpg",
    },
    {
      id: 2,
      title: "Lotus Herbals - Anti Ageing Facial",
      price: 920,
      oldPrice: 1540,
      discount: "40% Off",
      duration: "45 MINS",
      img: "/aa1.jpg",
    },
    {
      id: 3,
      title: "Cheryl's VitalLift Facial For Anti-Ageing",
      price: 1098,
      oldPrice: 1499,
      discount: "27% Off",
      duration: "45 MINS",
      img: "/aa2.jpg",
    },
    {
      id: 4,
      title: "O3+ Anti Ageing Facial",
      price: 1799,
      oldPrice: 2999,
      discount: "40% Off",
      duration: "60 MINS",
      img: "/aa3.jpg",
    },
  ],
  "nail-art": [
    {
      id: 1,
      title: "Basic Nail Art",
      price: 499,
      oldPrice: 799,
      discount: "38% Off",
      duration: "45 MINS",
      img: "/n1.jpg",
    },
    {
      id: 2,
      title: "Premium Nail Art",
      price: 899,
      oldPrice: 1499,
      discount: "40% Off",
      duration: "60 MINS",
      img: "/n2.jpg",
    },
    {
      id: 3,
      title: "Bridal Nail Art",
      price: 1199,
      oldPrice: 1999,
      discount: "40% Off",
      duration: "75 MINS",
      img: "/n3.jpg",
    },
    {
      id: 4,
      title: "Gel Nail Extension",
      price: 1499,
      oldPrice: 2499,
      discount: "40% Off",
      duration: "90 MINS",
      img: "/n4.jpg",
    },
    {
      id: 5,
      title: "3D Nail Art",
      price: 1799,
      oldPrice: 2999,
      discount: "40% Off",
      duration: "100 MINS",
      img: "/n5.jpg",
    },
    {
      id: 6,
      title: "Stone Work Nail Art",
      price: 999,
      oldPrice: 1699,
      discount: "41% Off",
      duration: "60 MINS",
      img: "/n6.jpg",
    },
    {
      id: 7,
      title: "Glitter Nail Art",
      price: 699,
      oldPrice: 1199,
      discount: "42% Off",
      duration: "50 MINS",
      img: "/n7.jpg",
    },
    {
      id: 8,
      title: "French Nail Art",
      price: 899,
      oldPrice: 1399,
      discount: "36% Off",
      duration: "55 MINS",
      img: "/n8.jpg",
    },
    {
      id: 9,
      title: "Custom Designer Nail Art",
      price: 1499,
      oldPrice: 2499,
      discount: "40% Off",
      duration: "90 MINS",
      img: "/n9.jpg",
    },
    {
      id: 10,
      title: "Full Bridal Nail Package",
      price: 1999,
      oldPrice: 3499,
      discount: "43% Off",
      duration: "120 MINS",
      img: "/n10.png",
    },
  ],
  "clean-up": [
    {
      id: 1,
      title: "VLCC Skin Cleanup",
      price: 499,
      oldPrice: 699,
      discount: "29% Off",
      duration: "30 MINS",
      img: "/cl.jpg",
    },
    {
      id: 2,
      title: "VLCC Insta Glow Clean Up",
      price: 599,
      oldPrice: 699,
      discount: "14% Off",
      duration: "30 MINS",
      img: "/aa.jpg",
    },
    {
      id: 3,
      title: "Lotus Cleanup",
      price: 499,
      oldPrice: 899,
      discount: "44% Off",
      duration: "30 MINS",
      img: "/cl1.jpg",
    },
    {
      id: 4,
      title: "SARA Green Apple Cleanup By O3+",
      price: 849,
      oldPrice: 1199,
      discount: "29% Off",
      duration: "30 MINS",
      img: "/cl2.jpg",
    },
  ],
  "party-make-up": [
    {
      id: 1,
      title: "Party Makeup",
      price: 1799,
      oldPrice: 3999,
      discount: "55% Off",
      duration: "90 MINS",
      img: "/party.jpg",
    },
    {
      id: 2,
      title: "Luxury Party Makeup",
      price: 4599,
      oldPrice: 8999,
      discount: "49% Off",
      duration: "90 MINS",
      img: "/lux.jpg",
    },
    {
      id: 3,
      title: "HD Party Makeup",
      price: 6599,
      oldPrice: 7999,
      discount: "18% Off",
      duration: "100 MINS",
      img: "/hd.jpg",
    },
  ],
  "engagement-make-up": [
    {
      id: 1,
      title: "Luxury Engagement Make Up",
      price: 3999,
      oldPrice: 7999,
      discount: "50% Off",
      duration: "120 MINS",
      img: "/le.jpg",
    },
    {
      id: 2,
      title: "HD Engagement Make Up",
      price: 5099,
      oldPrice: 10198,
      discount: "50% Off",
      duration: "120 MINS",
      img: "/le1.jpg",
    },
    {
      id: 3,
      title: "Air Brush Engagement Make Up",
      price: 6999,
      oldPrice: 12999,
      discount: "50% Off",
      duration: "120 MINS",
      img: "/le2.jpg",
    },
  ],
  "bridal-make-up": [
    {
      id: 1,
      title: "Luxury Bridal Makeup",
      price: 9599,
      oldPrice: 18000,
      discount: "47% Off",
      duration: "180 MINS",
      img: "/bm.jpg",
    },
    {
      id: 2,
      title: "HD Bridal Makeup",
      price: 10499,
      oldPrice: 20998,
      discount: "50% Off",
      duration: "160 MINS",
      img: "/bm1.jpg",
    },
    {
      id: 3,
      title: "Air Brush Bridal Makeup",
      price: 15499,
      oldPrice: 30998,
      discount: "50% Off",
      duration: "200 MINS",
      img: "/bm2.jpg",
    },
  ],
  "group-deals": [
    {
      id: 1,
      title: "Luxury Party Group Makeup",
      price: 8499,
      oldPrice: 16998,
      discount: "50% Off",
      duration: "300 MINS",
      img: "/hd.jpg",
    },
    {
      id: 2,
      title: "HD Group Party  Makeup",
      price: 11499,
      oldPrice: 22998,
      discount: "50% Off",
      duration: "320 MINS",
      img: "/bm2.jpg",
    },
  ],
  "hair-styling": [
    {
      id: 1,
      title: "Blow Dry",
      price: 499,
      oldPrice: 998,
      discount: "50% Off",
      duration: "30 MINS",
      img: "/h.png",
    },
    {
      id: 2,
      title: "Straightening",
      price: 499,
      oldPrice: 998,
      discount: "50% Off",
      duration: "35 MINS",
      img: "/h1.png",
    },
    {
      id: 3,
      title: "Hair Curl",
      price: 499,
      oldPrice: 998,
      discount: "50% Off",
      duration: "35 MINS",
      img: "/h2.png",
    },
    {
      id: 4,
      title: "Advance Hair DO",
      price: 990,
      oldPrice: 1599,
      discount: "38% Off",
      duration: "40 MINS",
      img: "/h3.png",
    },
    {
      id: 5,
      title: "Basic Gropu Hair Styling",
      price: 1999,
      oldPrice: 3999,
      discount: "50% Off",
      duration: "150 MINS",
      img: "/h4.png",
    },
  ],
  "saree-draping": [
    {
      id: 1,
      title: "Saree Draping",
      price: 350,
      oldPrice: 699,
      discount: "50% Off",
      duration: "20 MINS",
      img: "/saree.png",
    },
  ],
  "bleach": [
    {
      id: 1,
      title: "Full Face & Neck Bleach",
      price: 299,
      oldPrice: 349,
      discount: "14% Off",
      duration: "20 MINS",
      img: "/b.jpg",
    },
    {
      id: 2,
      title: "Full Arms Bleach",
      price: 399,
      oldPrice: 450,
      discount: "11% Off",
      duration: "20 MINS",
      img: "/b1.jpg",
    },
    {
      id: 3,
      title: "Under Arms Bleach",
      price: 249,
      oldPrice: 300,
      discount: "17% Off",
      duration: "10 MINS",
      img: "/b2.jpg",
    },
    {
      id: 4,
      title: "Full Legs Bleach",
      price: 589,
      oldPrice: 699,
      discount: "16% Off",
      duration: "20 MINS",
      img: "/b3.jpg",
    },
    {
      id: 5,
      title: "Half Legs Bleach",
      price: 289,
      oldPrice: 399,
      discount: "28% Off",
      duration: "15 MINS",
      img: "/b4.jpg",
    },
    {
      id: 6,
      title: "Front Bleach",
      price: 499,
      oldPrice: 599,
      discount: "17% Off",
      duration: "20 MINS",
      img: "/b5.jpg",
    },
    {
      id: 7,
      title: "Stomach Bleach",
      price: 389,
      oldPrice: 429,
      discount: "9% Off",
      duration: "20 MINS",
      img: "/b5.jpg",
    },
    {
      id: 8,
      title: "Half Back Bleach",
      price: 389,
      oldPrice: 420,
      discount: "9% Off",
      duration: "20 MINS",
      img: "/b7.jpg",
    },
    {
      id: 9,
      title: "Full Back Bleach",
      price: 499,
      oldPrice: 599,
      discount: "17% Off",
      duration: "20 MINS",
      img: "/b8.jpg",
    },
    {
      id: 10,
      title: "Full Body Bleach",
      price: 1099,
      oldPrice: 1599,
      discount: "31% Off",
      duration: "45 MINS",
      img: "/b9.jpg",
    },
    {
      id: 11,
      title: "Full Body Bleach + Face & Neck",
      price: 1299,
      oldPrice: 1899,
      discount: "32% Off",
      duration: "60 MINS",
      img: "/b10.jpg",
    },
  ],
  "de-tan": [
    {
      id: 1,
      title: "Face & Neck Detan Pack",
      price: 399,
      oldPrice: 449,
      discount: "11% Off",
      duration: "20 MINS",
      img: "/d.jpg",
    },
    {
      id: 2,
      title: "Full Hand De-tan",
      price: 499,
      oldPrice: 549,
      discount: "9% Off",
      duration: "20 MINS",
      img: "/d1.jpg",
    },
    {
      id: 3,
      title: "Under Arms De-tan",
      price: 199,
      oldPrice: 249,
      discount: "20% Off",
      duration: "20 MINS",
      img: "/d2.jpg",
    },
    {
      id: 4,
      title: "Full Legs De-tan",
      price: 449,
      oldPrice: 549,
      discount: "18% Off",
      duration: "20 MINS",
      img: "/d3.jpg",
    },
    {
      id: 5,
      title: "Full Front De-tan",
      price: 499,
      oldPrice: 549,
      discount: "9% Off",
      duration: "20 MINS",
      img: "/d4.jpg",
    },
    {
      id: 6,
      title: "Half Back De-tan",
      price: 329,
      oldPrice: 380,
      discount: "13% Off",
      duration: "15 MINS",
      img: "/d5.jpg",
    },
    {
      id: 7,
      title: "Full Back De-tan",
      price: 499,
      oldPrice: 549,
      discount: "9% Off",
      duration: "30 MINS",
      img: "/d6.jpg",
    },
    {
      id: 8,
      title: "Full Body De-tan",
      price: 1199,
      oldPrice: 1599,
      discount: "25% Off",
      duration: "45 MINS",
      img: "/d7.jpg",
    },
    {
      id: 9,
      title: "Full Body De-tan + Face & Neck",
      price: 1299,
      oldPrice: 1999,
      discount: "35% Off",
      duration: "60 MINS",
      img: "/d8.jpg",
    },
  ],
  "honey-waxing": [
    {
      id: 1,
      title: "Honey Full Body + Bikini",
      price: 1499,
      oldPrice: 2499,
      discount: "40% Off",
      duration: "75 MINS",
      img: "/wh.jpg",
    },
    {
      id: 2,
      title: "Honey Full Body Wax",
      price: 1199,
      oldPrice: 1499,
      discount: "20% Off",
      duration: "60 MINS",
      img: "/wh1.jpg",
    },
    {
      id: 3,
      title: "Honey Bikini Wax Package",
      price: 1319,
      oldPrice: 2250,
      discount: "41% Off",
      duration: "75 MINS",
      img: "/wh2.jpg",
    },
    {
      id: 4,
      title: "Honey Wax Package",
      price: 729,
      oldPrice: 999,
      discount: "27% Off",
      duration: "60 MINS",
      img: "/wh3.jpg",
    },
    {
      id: 5,
      title: "Full Arms With Under Arms - Honey Wax",
      price: 299,
      oldPrice: 399,
      discount: "25% Off",
      duration: "20 MINS",
      img: "/wh4.jpg",
    },
    {
      id: 6,
      title: "Full Arms(Without Underms) - Honey Wax",
      price: 345,
      oldPrice: 380,
      discount: "9% Off",
      duration: "15 MINS",
      img: "/wh5.jpg",
    },
    {
      id: 7,
      title: "Half Arms - Honey Wax",
      price: 249,
      oldPrice: 299,
      discount: "17% Off",
      duration: "15 MINS",
      img: "/wh6.jpg",
    },
    {
      id: 8,
      title: "Under Arms - Honey Wax",
      price: 89,
      oldPrice: 109,
      discount: "18% Off",
      duration: "10 MINS",
      img: "/wh7.jpg",
    },
    {
      id: 9,
      title: "Full Legs - Honey Wax",
      price: 399,
      oldPrice: 499,
      discount: "20% Off",
      duration: "25 MINS",
      img: "/wh8.jpg",
    },
    {
      id: 10,
      title: "Half Legs - Honey Wax",
      price: 335,
      oldPrice: 370,
      discount: "9% Off",
      duration: "20 MINS",
      img: "/wh9.jpg",
    },
    {
      id: 11,
      title: "Full Back - Honey Wax",
      price: 489,
      oldPrice: 580,
      discount: "16% Off",
      duration: "20 MINS",
      img: "/wh10.jpg",
    },
    {
      id: 12,
      title: "Half Back - Honey Wax",
      price: 280,
      oldPrice: 380,
      discount: "26% Off",
      duration: "20 MINS",
      img: "/wh11.jpg",
    },
    {
      id: 13,
      title: "Stomach - Honey Wax",
      price: 379,
      oldPrice: 399,
      discount: "5% Off",
      duration: "25 MINS",
      img: "/wh12.jpg",
    },
    {
      id: 14,
      title: "Buttock - Honey Wax",
      price: 399,
      oldPrice: 499,
      discount: "20% Off",
      duration: "15 MINS",
      img: "/wh13.jpg",
    },
    {
      id: 15,
      title: "Bikini Waxing - Honey Wax",
      price: 699,
      oldPrice: 899,
      discount: "22% Off",
      duration: "25 MINS",
      img: "/wh14.jpg",
    },
  ],
  "rica-waxing": [
    {
      id: 1,
      title: "RICA Full Body + Bikini",
      price: 2299,
      oldPrice: 3599,
      discount: "36% Off",
      duration: "36 MINS",
      img: "/wr.jpg",
    },
    {
      id: 2,
      title: "RICA Full Body",
      price: 1899,
      oldPrice: 3199,
      discount: "41% Off",
      duration: "60 MINS",
      img: "/wr1.jpg",
    },
    {
      id: 3,
      title: "RICA Bikini Wax Package",
      price: 1699,
      oldPrice: 3299,
      discount: "48% Off",
      duration: "80 MINS",
      img: "/wr2.jpg",
    },
    {
      id: 4,
      title: "RICA Wax Package",
      price: 949,
      oldPrice: 1650,
      discount: "42% Off",
      duration: "45 MINS",
      img: "/wr3.jpg",
    },
    {
      id: 5,
      title: "Full Arms With Under Arms - RICA Wax",
      price: 699,
      oldPrice: 899,
      discount: "22% Off",
      duration: "30 MINS",
      img: "/wr4.jpg",
    },
    {
      id: 6,
      title: "Full Arms (Without Underarms) - RICA Wax",
      price: 599,
      oldPrice: 745,
      discount: "20% Off",
      duration: "20 MINS",
      img: "/wr5.jpg",
    },
    {
      id: 7,
      title: "Half Arms - RICA Wax",
      price: 489,
      oldPrice: 649,
      discount: "25% Off",
      duration: "15 MINS",
      img: "/wr6.jpg",
    },

    {
      id: 8,
      title: "Under Arms - RICA Wax",
      price: 149,
      oldPrice: 199,
      discount: "25% Off",
      duration: "10 MINS",
      img: "/wr7.jpg",
    },
    {
      id: 9,
      title: "Full Legs - RICA Wax",
      price: 699,
      oldPrice: 899,
      discount: "22% Off",
      duration: "30 MINS",
      img: "/wr8.jpg",
    },
    {
      id: 10,
      title: "Half Legs - RICA Wax",
      price: 449,
      oldPrice: 599,
      discount: "25% Off",
      duration: "15 MINS",
      img: "/wr9.jpg",
    },
    {
      id: 11,
      title: "Full Back - RICA Wax",
      price: 499,
      oldPrice: 899,
      discount: "44% Off",
      duration: "20 MINS",
      img: "/wr10.jpg",
    },
    {
      id: 12,
      title: "Half Back - RICA Wax",
      price: 429,
      oldPrice: 799,
      discount: "46% Off",
      duration: "15 MINS",
      img: "/wr11.jpg",
    },
    {
      id: 13,
      title: "Stomach - RICA Wax",
      price: 429,
      oldPrice: 799,
      discount: "46% Off",
      duration: "15 MINS",
      img: "/wr12.jpg",
    },
    {
      id: 14,
      title: "Buttock - RICA Wax",
      price: 409,
      oldPrice: 699,
      discount: "41% Off",
      duration: "25 MINS",
      img: "/wr13.jpg",
    },
    {
      id: 15,
      title: "Bikini Waxing - RICA Wax",
      price: 849,
      oldPrice: 1599,
      discount: "47% Off",
      duration: "45 MINS",
      img: "/wr14.jpg",
    },
    {
      id: 16,
      title: "Bikini Line/Butt Line - RICA Wax",
      price: 249,
      oldPrice: 399,
      discount: "38% Off",
      duration: "25 MINS",
      img: "/wr15.jpg",
    },
  ],
  "rica-brazilian": [
    {
      id: 1,
      title: "Bikini Wax Rica Brazilians",
      price: 999,
      oldPrice: 1699,
      discount: "41% Off",
      duration: "25 MINS",
      img: "/rb.jpg",
    },
    {
      id: 2,
      title: "Full Face - RICA Brazilian Wax",
      price: 399,
      oldPrice: 699,
      discount: "43% Off",
      duration: "25 MINS",
      img: "/rb1.jpg",
    },
    {
      id: 3,
      title: "Upper Lip Rica Brazilian Wax",
      price: 55,
      oldPrice: 99,
      discount: "44% Off",
      duration: "10 MINS",
      img: "/rb2.jpg",
    },
    {
      id: 4,
      title: "Chin-Rica Brazilian Wax",
      price: 80,
      oldPrice: 149,
      discount: "46% Off",
      duration: "10 MINS",
      img: "/rb3.jpg",
    },
    {
      id: 5,
      title: "Forehead Rica Brazilian Wax",
      price: 120,
      oldPrice: 199,
      discount: "40% Off",
      duration: "15 MINS",
      img: "/rb4.jpg",
    },
    {
      id: 6,
      title: "Under Arms Rica Brazilian Wax",
      price: 189,
      oldPrice: 279,
      discount: "32% Off",
      duration: "10 MINS",
      img: "/rb5.jpg",
    },
    {
      id: 7,
      title: "Side Lock - Rica Brazilian Wax",
      price: 148,
      oldPrice: 249,
      discount: "41% Off",
      duration: "15 MINS",
      img: "/rb6.jpg",
    },
    {
      id: 8,
      title: "Buttock - Rica Brazilian Wax",
      price: 698,
      oldPrice: 999,
      discount: "30% Off",
      duration: "20 MINS",
      img: "/rb7.jpg",
    },
  ],
  "rica-roll-on": [
    {
      id: 1,
      title: "Roll-On Full Body + Bikini",
      price: 2699,
      oldPrice: 3999,
      discount: "33% Off",
      duration: "120 MINS",
      img: "/rr.jpg",
    },
    {
      id: 2,
      title: "Full Body Rica Roll-On",
      price: 2099,
      oldPrice: 3299,
      discount: "36% Off",
      duration: "80 MINS",
      img: "/rr1.jpg",
    },
    {
      id: 3,
      title: "RICA Roll-On Package",
      price: 949,
      oldPrice: 1699,
      discount: "44% Off",
      duration: "45 MINS",
      img: "/rr2.jpg",
    },
    {
      id: 4,
      title: "Full Arms With Under Arms - Rica Roll On",
      price: 599,
      oldPrice: 899,
      discount: "33% Off",
      duration: "35 MINS",
      img: "/rr3.jpg",
    },
    {
      id: 5,
      title: "Full Arms (Without Underarms)- RICA Roll-On",
      price: 519,
      oldPrice: 799,
      discount: "35% Off",
      duration: "30 MINS",
      img: "/rr4.jpg",
    },
    {
      id: 6,
      title: "Full Legs - Rica Roll-On",
      price: 649,
      oldPrice: 1299,
      discount: "50% Off",
      duration: "35 MINS",
      img: "/rr5.jpg",
    },
    {
      id: 7,
      title: "Half Legs - Roll-On",
      price: 499,
      oldPrice: 999,
      discount: "50% Off",
      duration: "20 MINS",
      img: "/rr6.jpg",
    },
    {
      id: 8,
      title: "Full Back - Rica Roll-On",
      price: 599,
      oldPrice: 1199,
      discount: "50% Off",
      duration: "40 MINS",
      img: "/rr7.jpg",
    },
    {
      id: 9,
      title: "Half Back - RICA Roll-On",
      price: 549,
      oldPrice: 1049,
      discount: "48% Off",
      duration: "25 MINS",
      img: "/rr8.jpg",
    },
    {
      id: 10,
      title: "Stomach - Rica Roll-On",
      price: 549,
      oldPrice: 1049,
      discount: "48% Off",
      duration: "25 MINS",
      img: "/rr9.jpg",
    },
  ],
  "medi-pedi": [
    {
      id: 1,
      title: "Classic Manicure-Pedicure",
      price: 599,
      oldPrice: 1299,
      discount: "54% Off",
      duration: "60 MINS",
      img: "/mp.jpg",
    },
    {
      id: 2,
      title: "Aroma Magic Manicure-Pedicure",
      price: 799,
      oldPrice: 1299,
      discount: "38% Off",
      duration: "60 MINS",
      img: "/mp1.jpg",
    },
    {
      id: 3,
      title: "O3+ Bubblegum Manicure-Pedicure",
      price: 1199,
      oldPrice: 1899,
      discount: "37% Off",
      duration: "60 MINS",
      img: "/mp2.jpg",
    },
    {
      id: 4,
      title: "Sara DeTan/Rose Manicure-Pedicure",
      price: 999,
      oldPrice: 1599,
      discount: "38% Off",
      duration: "60 MINS",
      img: "/mp3.jpg",
    },
  ],
  "medicure": [
    {
      id: 1,
      title: "CLassic Manicure",
      price: 349,
      oldPrice: 599,
      discount: "42% Off",
      duration: "30 MINS",
      img: "/m.png",
    },
    {
      id: 2,
      title: "Aroma Magic Manicure",
      price: 399,
      oldPrice: 599,
      discount: "33% Off",
      duration: "30 MINS",
      img: "/m1.png",
    },
    {
      id: 3,
      title: "O3+ Bubblegum Manicure",
      price: 699,
      oldPrice: 1199,
      discount: "42% Off",
      duration: "30 MINS",
      img: "/m2.jpg",
    },
    {
      id: 4,
      title: "Sara DeTan/Rose Manicure",
      price: 499,
      oldPrice: 899,
      discount: "44% Off",
      duration: "30 MINS",
      img: "/m3.jpg",
    },
    {
      id: 5,
      title: "File Cut Polish",
      price: 149,
      oldPrice: 250,
      discount: "40% Off",
      duration: "15 MINS",
      img: "/m4.png",
    },
  ],
  "pedicure": [
    {
      id: 1,
      title: "CLassic Pedicure",
      price: 399,
      oldPrice: 599,
      discount: "33% Off",
      duration: "30 MINS",
      img: "/p.jpg",
    },
    {
      id: 2,
      title: "Aroma Magic Pedicure",
      price: 499,
      oldPrice: 689,
      discount: "28% Off",
      duration: "30 MINS",
      img: "/p1.jpg",
    },
    {
      id: 3,
      title: "O3+ Bubblegum Pedicure",
      price: 799,
      oldPrice: 1499,
      discount: "47% Off",
      duration: "30 MINS",
      img: "/p2.jpg",
    },
    {
      id: 4,
      title: "Sara DeTan/Rose Pedicure",
      price: 599,
      oldPrice: 1199,
      discount: "50% Off",
      duration: "30 MINS",
      img: "/p3.jpg",
    },
  ],
  "hair-cut": [
    {
      id: 1,
      title: "Feather Haircut",
      price: 549,
      oldPrice: 899,
      discount: "39% Off",
      duration: "40 MINS",
      img: "/hc.jpg",
    },
    {
      id: 2,
      title: "Step Haircut",
      price: 549,
      oldPrice: 899,
      discount: "39% Off",
      duration: "40 MINS",
      img: "/hc1.jpg",
    },
    {
      id: 3,
      title: "U Shape Haircut",
      price: 349,
      oldPrice: 699,
      discount: "50% Off",
      duration: "25 MINS",
      img: "/hc2.jpg",
    },
    {
      id: 4,
      title: "V Shape Haircut",
      price: 549,
      oldPrice: 899,
      discount: "39% Off",
      duration: "30 MINS",
      img: "/hc3.jpg",
    },
    {
      id: 5,
      title: "One Length Haircut",
      price: 549,
      oldPrice: 899,
      discount: "39% Off",
      duration: "35 MINS",
      img: "/hc4.jpg",
    },
    {
      id: 6,
      title: "Front Layer Haircut",
      price: 399,
      oldPrice: 599,
      discount: "33% Off",
      duration: "25 MINS",
      img: "/hc5.jpg",
    },
    {
      id: 7,
      title: "Split Ends Haircut",
      price: 349,
      oldPrice: 549,
      discount: "36% Off",
      duration: "25 MINS",
      img: "/hc6.jpg",
    },
    {
      id: 8,
      title: "Bob Cut",
      price: 559,
      oldPrice: 899,
      discount: "38% Off",
      duration: "30 MINS",
      img: "/hc7.jpg",
    },
    {
      id: 9,
      title: "Cara Bob Haircut",
      price: 599,
      oldPrice: 899,
      discount: "33% Off",
      duration: "30 MINS",
      img: "/hc8.jpg",
    },
    {
      id: 10,
      title: "Multi-Layer Cutting",
      price: 549,
      oldPrice: 899,
      discount: "39% Off",
      duration: "30 MINS",
      img: "/hc9.jpg",
    },
  ],
  "hair-spa": [
    {
      id: 1,
      title: "L'oreal Hair Spa - S",
      price: 649,
      oldPrice: 1399,
      discount: "54% Off",
      duration: "40 MINS",
      img: "/hs.png",
    },
    {
      id: 2,
      title: "L'oreal Hair Spa - M",
      price: 849,
      oldPrice: 169,
      discount: "50% Off",
      duration: "40 MINS",
      img: "/hs1.png",
    },
    {
      id: 3,
      title: "L'oreal Hair Spa - L",
      price: 1199,
      oldPrice: 2399,
      discount: "50% Off",
      duration: "50 MINS",
      img: "/hs2.png",
    },
    {
      id: 4,
      title: "L'oreal Dry And Sensitive Scalp Ampoule",
      price: 120,
      oldPrice: 299,
      discount: "60% Off",
      duration: "10 MINS",
      img: "/hs3.png",
    },
    {
      id: 5,
      title: "L'oreal Anti Dandruff Ampoule",
      price: 149,
      oldPrice: 299,
      discount: "50% Off",
      duration: "10 MINS",
      img: "/hs4.png",
    },
  ],
  "hair-color": [
    {
      id: 1,
      title: "Loreal INOA Root Touch Up",
      price: 849,
      oldPrice: 1699,
      discount: "50% Off",
      duration: "45 MINS",
      img: "/ch.png",
    },
    {
      id: 2,
      title: "Loreal Majirel-Root Touch Up",
      price: 699,
      oldPrice: 1399,
      discount: "50% Off",
      duration: "40 MINS",
      img: "/ch1.jpg",
    },
    {
      id: 3,
      title: "Loreal INOA Global-Small",
      price: 1349,
      oldPrice: 2699,
      discount: "50% Off",
      duration: "45 MINS",
      img: "/ch2.png",
    },
    {
      id: 4,
      title: "L'oreal Majirel Global-Small",
      price: 1200,
      oldPrice: 2400,
      discount: "50% Off",
      duration: "45 MINS",
      img: "/ch3.jpg",
    },
    {
      id: 5,
      title: "Loreal INOA Global-Medium",
      price: 2100,
      oldPrice: 4199,
      discount: "50% Off",
      duration: "60 MINS",
      img: "/ch4.png",
    },
    {
      id: 6,
      title: "Loreal Majirel Global-Medium",
      price: 1900,
      oldPrice: 3799,
      discount: "50% Off",
      duration: "60 MINS",
      img: "/ch5.jpg",
    },
    {
      id: 7,
      title: "Loreal INOA Global-Large",
      price: 2599,
      oldPrice: 5199,
      discount: "50% Off",
      duration: "75 MINS",
      img: "/ch6.png",
    },
    {
      id: 8,
      title: "Loreal Majirel Global-Large",
      price: 2400,
      oldPrice: 4799,
      discount: "50% Off",
      duration: "75 MINS",
      img: "/ch7.jpg",
    },
    {
      id: 9,
      title: "Henna/Colour Application",
      price: 350,
      oldPrice: 699,
      discount: "50% Off",
      duration: "20 MINS",
      img: "/ch8.jpg",
    },
  ],
  "hair-highlights": [
    {
      id: 1,
      title: "Hair Highlights",
      price: 350,
      oldPrice: 699,
      discount: "50% Off",
      duration: "20 MINS",
      img: "/ch7.jpg",
    },
  ],
  "hair-treatments": [
    {
      id: 1,
      title: "Schwarzkopf Smoothing Small Hair Length",
      price: 2999,
      oldPrice: 3999,
      discount: "25% Off",
      duration: "240 MINS",
      img: "/ht.jpg",
    },
    {
      id: 2,
      title: "Schwarzkopf Smoothing Medium Hair Length",
      price: 3599,
      oldPrice: 4599,
      discount: "22% Off",
      duration: "240 MINS",
      img: "/ht1.jpg",
    },
    {
      id: 3,
      title: "Schwarzkopf Smoothing Large Hair Length",
      price: 3999,
      oldPrice: 4999,
      discount: "20% Off",
      duration: "280 MINS",
      img: "/ht2.jpg",
    },
    {
      id: 4,
      title: "Keratin Treatment - Small Hair Length",
      price: 2599,
      oldPrice: 5299,
      discount: "51% Off",
      duration: "240 MINS",
      img: "/ht3.jpg",
    },
    {
      id: 5,
      title: "Keratin Treatment - Medium Hair Length",
      price: 2999,
      oldPrice: 6299,
      discount: "52% Off",
      duration: "240 MINS",
      img: "/ht4.jpg",
    },
    {
      id: 6,
      title: "Keratin Treatment - Large Hair Length",
      price: 3799,
      oldPrice: 7299,
      discount: "48% Off",
      duration: "280 MINS",
      img: "/ht5.jpg",
    },
  ],
  "pre-bridal": [
    {
      id: 2,
      title: "Luxury Pre-Bridal Grooming",
      price: 6999,
      oldPrice: 9500,
      discount: "26% Off",
      duration: "420 MINS",
      img: "/pb1.jpg",
    },
    {
      id: 1,
      title: "Classic Pre-Bridal Grooming",
      price: 5299,
      oldPrice: 8500,
      discount: "38% Off",
      duration: "330 MINS",
      img: "/pb.jpg",
    },
    {
      id: 3,
      title: "Magnificence Pre-Bridal Grooming",
      price: 7699,
      oldPrice: 9999,
      discount: "20% Off",
      duration: "570 MINS",
      img: "/pb2.jpg",
    },
  ],
  "threading": [
    {
      id: 1,
      title: "Eye Brows Threading",
      price: 30,
      oldPrice: 50,
      discount: "40% Off",
      duration: "5 MINS",
      img: "/t.jpg",
    },
    {
      id: 2,
      title: "Forehead Threading",
      price: 30,
      oldPrice: 50,
      discount: "40% Off",
      duration: "5 MINS",
      img: "/t1.jpg",
    },
    {
      id: 3,
      title: "Chin Threading",
      price: 30,
      oldPrice: 50,
      discount: "40% Off",
      duration: "5 MINS",
      img: "/t2.jpg",
    },
    {
      id: 4,
      title: "Threading Upper Lips",
      price: 30,
      oldPrice: 50,
      discount: "40% Off",
      duration: "5 MINS",
      img: "/t3.jpg",
    },
    {
      id: 5,
      title: "Full Face Threading",
      price: 139,
      oldPrice: 250,
      discount: "44% Off",
      duration: "20 MINS",
      img: "/t4.jpg",
    },
    {
      id: 6,
      title: "Threading Side Lock",
      price: 30,
      oldPrice: 50,
      discount: "40% Off",
      duration: "5 MINS",
      img: "/t5.jpg",
    },
  ],
};

export default function PackagesPage() {
  const [activeCategory, setActiveCategory] = useState("packages-deals");
  const [activeSub, setActiveSub] = useState("classic-skin");
  const [sidebarOpen, setSidebarOpen] = useState(false);

  // Ref to scroll to the content section
  const contentRef = useRef(null);

  // Scroll to content whenever category/sub changes
  useEffect(() => {
    if (contentRef.current) {
      contentRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [activeSub]);


  const navigate = useNavigate();

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between md:justify-start gap-3 mb-4">
        {/* Menu button on left */}
        <button
          className="p-2 rounded-md bg-pink-500 text-white md:hidden"
          onClick={() => setSidebarOpen(!sidebarOpen)}
        >
          {sidebarOpen ? <X size={22} /> : <Menu size={22} />}
        </button>
        <h2 className="text-xl md:text-2xl font-bold justify-center">
          Services
        </h2>
      </div>

      <div className="flex flex-col md:flex-row gap-6">
        {/* Sidebar */}
        <aside
          className={`shadow-2xl rounded-lg p-4 w-full md:w-64 md:block
          ${sidebarOpen ? "block" : "hidden"} md:block`}
        >
          <h3 className="text-lg font-semibold mb-4">Categories</h3>
          <ul className="space-y-3">
            {categories.map((cat) => (
              <li key={cat.id}>
                <div
                  className={`cursor-pointer px-3 py-2 rounded-md flex items-center justify-between ${
                    activeCategory === cat.id
                      ? "bg-pink-100 text-pink-600 font-bold"
                      : "hover:bg-gray-50"
                  }`}
                  onClick={() => {
                    setActiveCategory(cat.id);
                    if (cat.sub.length > 0) setActiveSub(cat.sub[0].id);
                    if (window.innerWidth < 768) setSidebarOpen(false);
                  }}
                >
                  {cat.name}
                </div>
                {/* Subcategories */}
                {activeCategory === cat.id && cat.sub.length > 0 && (
                  <ul className="ml-5 mt-2 space-y-1 border-l-2 border-pink-300 pl-3">
                    {cat.sub.map((sub) => (
                      <li
                        key={sub.id}
                        className={`cursor-pointer text-sm px-2 py-1 rounded-md ${
                          activeSub === sub.id
                            ? "bg-pink-50 text-pink-600 font-semibold"
                            : "hover:bg-gray-100"
                        }`}
                        onClick={() => {
                          setActiveSub(sub.id);
                          if (window.innerWidth < 768) setSidebarOpen(false);
                        }}
                      >
                        {sub.name}
                      </li>
                    ))}
                  </ul>
                )}
              </li>
            ))}
          </ul>
        </aside>

        {/* Right Side Content */}
        <main className="flex-1" ref={contentRef}>
          <h2 className="text-2xl font-bold mb-6 capitalize">
            {activeSub.replace("-", " ")}
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-6">
            {services[activeSub]?.map((service, index) => (
              <motion.div
                key={service.id}
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: index * 0.1 }}
                className="rounded-xl shadow-lg overflow-hidden border bg-pink-50"
              >
                <div className="relative">
                  <img
                    src={service.img}
                    alt={service.title}
                    className="w-full h-45 object-cover"
                  />
                  {/* Duration */}
                  <span className="absolute top-3 left-3 bg-pink-600 text-white text-xs px-2 py-1 rounded">
                    {service.duration}
                  </span>
                  {/* Price Tag */}
                  <div className="absolute top-3 right-3 bg-pink-200 text-pink-700 text-sm font-bold px-3 py-1 rounded">
                    ₹ {service.price}{" "}
                    <span className="line-through text-gray-500 text-xs ml-1">
                      ₹ {service.oldPrice}
                    </span>{" "}
                    <span className="ml-1 text-pink-700">
                      {service.discount}
                    </span>
                  </div>
                </div>
                <div className="p-2">
                  <h3 className="text-lg font-semibold">{service.title}</h3>
                  <div className="mt-1 flex justify-center items-center">
                    <button
                      onClick={() => navigate('/booking')}
                      className="bg-teal-500 hover:bg-teal-600 text-white text-sm px-4 py-2 rounded-lg"
                    >
                      Book Now
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}